In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [45]:
data_path="House_Rent_Dataset.csv"
df=pd.read_csv(data_path)

In [46]:
df=df.drop(['Posted On','Area Locality','City','Point of Contact','Bathroom'],axis=1)

In [47]:
df=df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [48]:
df

,BHK,Rent,Size,Floor,Area Type,Furnishing Status,Tenant Preferred
0,2,10000,1100,Ground out of 2,Super Area,Unfurnished,Bachelors/Family
1,2,20000,800,1 out of 3,Super Area,Semi-Furnished,Bachelors/Family
2,2,17000,1000,1 out of 3,Super Area,Semi-Furnished,Bachelors/Family
3,2,10000,800,1 out of 2,Super Area,Unfurnished,Bachelors/Family
4,2,7500,850,1 out of 2,Carpet Area,Unfurnished,Bachelors
...,...,...,...,...,...,...,...
4741,2,15000,1000,3 out of 5,Carpet Area,Semi-Furnished,Bachelors/Family
4742,3,29000,2000,1 out of 4,Super Area,Semi-Furnished,Bachelors/Family
4743,3,35000,1750,3 out of 5,Carpet Area,Semi-Furnished,Bachelors/Family
4744,3,45000,1500,23 out of 34,Carpet Area,Semi-Furnished,Family
4745,2,15000,1000,4 out of 5,Carpet Area,Unfurnished,Bachelors

In [6]:
df.describe()

               BHK          Rent         Size
count  4650.000000  4.650000e+03  4650.000000
mean      2.089247  3.535450e+04   970.483011
std       0.834557  7.875412e+04   637.931735
min       1.000000  1.200000e+03    10.000000
25%       2.000000  1.000000e+04   550.000000
50%       2.000000  1.600000e+04   850.000000
75%       3.000000  3.400000e+04  1200.000000
max       6.000000  3.500000e+06  8000.000000

In [63]:
cols=['Rent','BHK','Size']

for col in cols:
    print(f"{col=}")
    for i in range(1,11):
        print(f"percentile{i*10}={np.percentile(df[col],i*10)}")
    print(f"percentile1 {np.percentile(df[col],1)}")
    print(f"percentile99 {np.percentile(df[col],99)}")

col='Rent'
percentile10=7000.0
percentile20=9000.0
percentile30=11000.0
percentile40=14000.0
percentile50=16000.0
percentile60=20000.0
percentile70=28000.0
percentile80=40000.0
percentile90=75000.0
percentile100=3500000.0
percentile1 4000.0
percentile99 300000.0
col='BHK'
percentile10=1.0
percentile20=1.0
percentile30=2.0
percentile40=2.0
percentile50=2.0
percentile60=2.0
percentile70=2.0
percentile80=3.0
percentile90=3.0
percentile100=6.0
percentile1 1.0
percentile99 4.0
col='Size'
percentile10=400.0
percentile20=500.0
percentile30=600.0
percentile40=720.6000000000001
percentile50=850.0
percentile60=1000.0
percentile70=1100.0
percentile80=1300.0
percentile90=1700.0
percentile100=8000.0
percentile1 68.98
percentile99 3300.0

In [8]:
plots = ['Rent', 'Size']

for col in plots:
    plt.figure()
    plt.hist(df[col], bins=25)
    plt.title(f"{col} Distribution")

    plt.savefig(f"{col}_distribution.png", dpi=300, bbox_inches='tight')
    plt.close()

In [9]:
outlier_cols=['Rent','Size']

for col in outlier_cols:
    df[col]=np.log1p(df[col])

In [10]:
df.describe()

               BHK         Rent         Size
count  4650.000000  4650.000000  4650.000000
mean      2.089247     9.888932     6.668866
std       0.834557     0.937887     0.710597
min       1.000000     7.090910     2.397895
25%       2.000000     9.210440     6.311735
50%       2.000000     9.680406     6.746412
75%       3.000000    10.434145     7.090910
max       6.000000    15.068274     8.987322

In [11]:
plots = ['Rent', 'Size']

for col in plots:
    plt.figure()
    plt.hist(df[col], bins=25)
    plt.title(f"{col} DistributionL")

    plt.savefig(f"{col}_distributionL.png", dpi=300, bbox_inches='tight')
    plt.close()

In [12]:
print(df['BHK'].unique())
print(df['Area Type'].unique())
print(df['Furnishing Status'].unique())
print(df['Tenant Preferred'].unique())

[2 1 3 6 4 5]
<StringArray>
['Super Area', 'Carpet Area', 'Built Area']
Length: 3, dtype: str
<StringArray>
['Unfurnished', 'Semi-Furnished', 'Furnished']
Length: 3, dtype: str
<StringArray>
['Bachelors/Family', 'Bachelors', 'Family']
Length: 3, dtype: str

In [13]:
df[['current_floor', 'total_floors']] = df['Floor'].str.extract(r'(\w+)\s*out of\s*(\d+)')
df['current_floor'] = df['current_floor'].replace(['Ground','Basement'], 0)

#4 columns will have nans so
df=df.dropna()

df['current_floor'] = df['current_floor'].astype(int)
df['total_floors'] = df['total_floors'].astype(int)
df=df.drop(['Floor'],axis=1)

In [14]:
df

,BHK,Rent,Size,Area Type,Furnishing Status,Tenant Preferred,current_floor,total_floors
0,2,9.210440,7.003974,Super Area,Unfurnished,Bachelors/Family,0,2
1,2,9.903538,6.685861,Super Area,Semi-Furnished,Bachelors/Family,1,3
2,2,9.741027,6.908755,Super Area,Semi-Furnished,Bachelors/Family,1,3
3,2,9.210440,6.685861,Super Area,Unfurnished,Bachelors/Family,1,2
4,2,8.922792,6.746412,Carpet Area,Unfurnished,Bachelors,1,2
...,...,...,...,...,...,...,...,...
4741,2,9.615872,6.908755,Carpet Area,Semi-Furnished,Bachelors/Family,3,5
4742,3,10.275086,7.601402,Super Area,Semi-Furnished,Bachelors/Family,1,4
4743,3,10.463132,7.467942,Carpet Area,Semi-Furnished,Bachelors/Family,3,5
4744,3,10.714440,7.313887,Carpet Area,Semi-Furnished,Family,23,34
4745,2,9.615872,6.908755,Carpet Area,Unfurnished,Bachelors,4,5

In [15]:
df['floor_ratio'] = df['current_floor'] / df['total_floors']
df.drop(['current_floor', 'total_floors'], axis=1, inplace=True)

In [16]:
df

,BHK,Rent,Size,Area Type,Furnishing Status,Tenant Preferred,floor_ratio
0,2,9.210440,7.003974,Super Area,Unfurnished,Bachelors/Family,0.000000
1,2,9.903538,6.685861,Super Area,Semi-Furnished,Bachelors/Family,0.333333
2,2,9.741027,6.908755,Super Area,Semi-Furnished,Bachelors/Family,0.333333
3,2,9.210440,6.685861,Super Area,Unfurnished,Bachelors/Family,0.500000
4,2,8.922792,6.746412,Carpet Area,Unfurnished,Bachelors,0.500000
...,...,...,...,...,...,...,...
4741,2,9.615872,6.908755,Carpet Area,Semi-Furnished,Bachelors/Family,0.600000
4742,3,10.275086,7.601402,Super Area,Semi-Furnished,Bachelors/Family,0.250000
4743,3,10.463132,7.467942,Carpet Area,Semi-Furnished,Bachelors/Family,0.600000
4744,3,10.714440,7.313887,Carpet Area,Semi-Furnished,Family,0.676471
4745,2,9.615872,6.908755,Carpet Area,Unfurnished,Bachelors,0.800000

In [17]:
categorial_cols=['Area Type','Furnishing Status','Tenant Preferred']
df=pd.get_dummies(df,columns=categorial_cols)

In [18]:
df

,BHK,Rent,Size,floor_ratio,Area Type_Built Area,Area Type_Carpet Area,Area Type_Super Area,Furnishing Status_Furnished,Furnishing Status_Semi-Furnished,Furnishing Status_Unfurnished,Tenant Preferred_Bachelors,Tenant Preferred_Bachelors/Family,Tenant Preferred_Family
0,2,9.210440,7.003974,0.000000,False,False,True,False,False,True,False,True,False
1,2,9.903538,6.685861,0.333333,False,False,True,False,True,False,False,True,False
2,2,9.741027,6.908755,0.333333,False,False,True,False,True,False,False,True,False
3,2,9.210440,6.685861,0.500000,False,False,True,False,False,True,False,True,False
4,2,8.922792,6.746412,0.500000,False,True,False,False,False,True,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4741,2,9.615872,6.908755,0.600000,False,True,False,False,True,False,False,True,False
4742,3,10.275086,7.601402,0.250000,False,False,True,False,True,False,False,True,False
4743,3,10.463132,7.467942,0.600000,False,True,False,False,True,False,False,True,False
4744,3,10.714440,7.313887,0.676471,False,True,False,False,True,False,False,False,True
4745,2,9.615872,6.908755,0.800000,False,True,False,False,False,True,True,False,False

In [19]:
bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(int)

In [20]:
df

,BHK,Rent,Size,floor_ratio,Area Type_Built Area,Area Type_Carpet Area,Area Type_Super Area,Furnishing Status_Furnished,Furnishing Status_Semi-Furnished,Furnishing Status_Unfurnished,Tenant Preferred_Bachelors,Tenant Preferred_Bachelors/Family,Tenant Preferred_Family
0,2,9.210440,7.003974,0.000000,0,0,1,0,0,1,0,1,0
1,2,9.903538,6.685861,0.333333,0,0,1,0,1,0,0,1,0
2,2,9.741027,6.908755,0.333333,0,0,1,0,1,0,0,1,0
3,2,9.210440,6.685861,0.500000,0,0,1,0,0,1,0,1,0
4,2,8.922792,6.746412,0.500000,0,1,0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4741,2,9.615872,6.908755,0.600000,0,1,0,0,1,0,0,1,0
4742,3,10.275086,7.601402,0.250000,0,0,1,0,1,0,0,1,0
4743,3,10.463132,7.467942,0.600000,0,1,0,0,1,0,0,1,0
4744,3,10.714440,7.313887,0.676471,0,1,0,0,1,0,0,0,1
4745,2,9.615872,6.908755,0.800000,0,1,0,0,0,1,1,0,0

In [21]:
scaler=StandardScaler()
df[['Rent','Size','BHK']]=scaler.fit_transform(df[['Rent','Size','BHK']])

In [22]:
df

,BHK,Rent,Size,floor_ratio,Area Type_Built Area,Area Type_Carpet Area,Area Type_Super Area,Furnishing Status_Furnished,Furnishing Status_Semi-Furnished,Furnishing Status_Unfurnished,Tenant Preferred_Bachelors,Tenant Preferred_Bachelors/Family,Tenant Preferred_Family
0,-0.106786,-0.723349,0.471349,0.000000,0,0,1,0,0,1,0,1,0
1,-0.106786,0.015425,0.023726,0.333333,0,0,1,0,1,0,0,1,0
2,-0.106786,-0.157795,0.337364,0.333333,0,0,1,0,1,0,0,1,0
3,-0.106786,-0.723349,0.023726,0.500000,0,0,1,0,0,1,0,1,0
4,-0.106786,-1.029954,0.108929,0.500000,0,1,0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4741,-0.106786,-0.291198,0.337364,0.600000,0,1,0,0,1,0,0,1,0
4742,1.091595,0.411459,1.312001,0.250000,0,0,1,0,1,0,0,1,0
4743,1.091595,0.611898,1.124207,0.600000,0,1,0,0,1,0,0,1,0
4744,1.091595,0.879768,0.907432,0.676471,0,1,0,0,1,0,0,0,1
4745,-0.106786,-0.291198,0.337364,0.800000,0,1,0,0,0,1,1,0,0

In [23]:
plots = ['Rent', 'Size']

for col in plots:
    plt.figure()
    plt.hist(df[col], bins=25)
    plt.title(f"{col} DistributionS")

    plt.savefig(f"{col}_distributionS.png", dpi=300, bbox_inches='tight')
    plt.close()

In [24]:
df

,BHK,Rent,Size,floor_ratio,Area Type_Built Area,Area Type_Carpet Area,Area Type_Super Area,Furnishing Status_Furnished,Furnishing Status_Semi-Furnished,Furnishing Status_Unfurnished,Tenant Preferred_Bachelors,Tenant Preferred_Bachelors/Family,Tenant Preferred_Family
0,-0.106786,-0.723349,0.471349,0.000000,0,0,1,0,0,1,0,1,0
1,-0.106786,0.015425,0.023726,0.333333,0,0,1,0,1,0,0,1,0
2,-0.106786,-0.157795,0.337364,0.333333,0,0,1,0,1,0,0,1,0
3,-0.106786,-0.723349,0.023726,0.500000,0,0,1,0,0,1,0,1,0
4,-0.106786,-1.029954,0.108929,0.500000,0,1,0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4741,-0.106786,-0.291198,0.337364,0.600000,0,1,0,0,1,0,0,1,0
4742,1.091595,0.411459,1.312001,0.250000,0,0,1,0,1,0,0,1,0
4743,1.091595,0.611898,1.124207,0.600000,0,1,0,0,1,0,0,1,0
4744,1.091595,0.879768,0.907432,0.676471,0,1,0,0,1,0,0,0,1
4745,-0.106786,-0.291198,0.337364,0.800000,0,1,0,0,0,1,1,0,0

In [25]:
x=df.values
x

array([[-0.10678648, -0.7233489 ,  0.47134862, ...,  0.        ,
         1.        ,  0.        ],
       [-0.10678648,  0.01542527,  0.02372587, ...,  0.        ,
         1.        ,  0.        ],
       [-0.10678648, -0.15779469,  0.33736376, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [ 1.09159516,  0.61189842,  1.12420655, ...,  0.        ,
         1.        ,  0.        ],
       [ 1.09159516,  0.87976838,  0.90743231, ...,  0.        ,
         0.        ,  1.        ],
       [-0.10678648, -0.29119807,  0.33736376, ...,  1.        ,
         0.        ,  0.        ]], shape=(4646, 13))

In [26]:
from sklearn.cluster import KMeans

inertia=[]

for k in range(1,11):
    kmeans=KMeans(n_clusters=k,random_state=42,n_init=10)
    kmeans.fit(x)
    inertia.append(kmeans.inertia_)

plt.figure()
plt.plot(range(1, 11), inertia, marker='o')
plt.title("Elbow Method")
plt.xlabel("K")
plt.ylabel("Inertia")

plt.savefig("elbow_method.png", dpi=300, bbox_inches='tight')
plt.close()

In [27]:
from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans

for k in range(2, 10):
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(x)
    score = silhouette_score(x, labels)
    print(k, score)

2 0.26488072275671687
3 0.1961757045027831
4 0.20298501095589178
5 0.21020664005031334
6 0.19591706347218152
7 0.2012742565573701
8 0.20877855887443017
9 0.2064042601581671

In [28]:
kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)
labels = kmeans.fit_predict(x)

df['Cluster']=labels

In [29]:
df['Cluster'].unique()

array([0, 4, 2, 1, 3], dtype=int32)

In [30]:
df

,BHK,Rent,Size,floor_ratio,Area Type_Built Area,Area Type_Carpet Area,Area Type_Super Area,Furnishing Status_Furnished,Furnishing Status_Semi-Furnished,Furnishing Status_Unfurnished,Tenant Preferred_Bachelors,Tenant Preferred_Bachelors/Family,Tenant Preferred_Family,Cluster
0,-0.106786,-0.723349,0.471349,0.000000,0,0,1,0,0,1,0,1,0,0
1,-0.106786,0.015425,0.023726,0.333333,0,0,1,0,1,0,0,1,0,0
2,-0.106786,-0.157795,0.337364,0.333333,0,0,1,0,1,0,0,1,0,0
3,-0.106786,-0.723349,0.023726,0.500000,0,0,1,0,0,1,0,1,0,0
4,-0.106786,-1.029954,0.108929,0.500000,0,1,0,0,0,1,1,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4741,-0.106786,-0.291198,0.337364,0.600000,0,1,0,0,1,0,0,1,0,4
4742,1.091595,0.411459,1.312001,0.250000,0,0,1,0,1,0,0,1,0,0
4743,1.091595,0.611898,1.124207,0.600000,0,1,0,0,1,0,0,1,0,1
4744,1.091595,0.879768,0.907432,0.676471,0,1,0,0,1,0,0,0,1,1
4745,-0.106786,-0.291198,0.337364,0.800000,0,1,0,0,0,1,1,0,0,4

In [31]:
data = {
    "BHK": [1,2,3,1,2,3,1,2,3,2],
    "Rent": [12000,18000,20000,10000,20000,30000,9000,22000,27000,15000],
    "Size": [450,700,1100,400,800,1300,750,850,1200,650],
    "Floor": ['2 out of 5','2 out of 3','0 out of 10','4 out of 6','6 out of 16','13 out of 16','9 out of 12','1 out of 5','3 out of 8','1 out of 2'],
    "Area Type": ["Carpet Area","Super Area","Built Area","Carpet Area","Super Area","Super Area","Carpet Area","Super Area","Carpet Area","Built Area"],
    "Furnishing Status": ["Semi-Furnished","Furnished","Furnished","Unfurnished","Semi-Furnished","Furnished","Unfurnished","Furnished","Semi-Furnished","Unfurnished"],
    "Tenant Preferred": ["Family","Family","Family","Bachelors","Bachelors/Family","Family","Bachelors","Family","Family","Bachelors"]
}

data2={
    "BHK": 1,
    "Rent":15000,
    "Size": None,
    "Floor": '1 out of 2',
    "Area Type":"Built Area",
    "Furnishing Status": "Semi-Furnished",
    "Tenant Preferred":None
}

In [32]:
dft=pd.DataFrame(data)
dft

,BHK,Rent,Size,Floor,Area Type,Furnishing Status,Tenant Preferred
0,1,12000,450,2 out of 5,Carpet Area,Semi-Furnished,Family
1,2,18000,700,2 out of 3,Super Area,Furnished,Family
2,3,20000,1100,0 out of 10,Built Area,Furnished,Family
3,1,10000,400,4 out of 6,Carpet Area,Unfurnished,Bachelors
4,2,20000,800,6 out of 16,Super Area,Semi-Furnished,Bachelors/Family
5,3,30000,1300,13 out of 16,Super Area,Furnished,Family
6,1,9000,750,9 out of 12,Carpet Area,Unfurnished,Bachelors
7,2,22000,850,1 out of 5,Super Area,Furnished,Family
8,3,27000,1200,3 out of 8,Carpet Area,Semi-Furnished,Family
9,2,15000,650,1 out of 2,Built Area,Unfurnished,Bachelors

In [33]:
def handle_missing(dict):
    bhk_med=2
    rent_med=16000
    size_med=850

    if(dict.get('BHK')==None):
        dict['BHK']=bhk_med
    
    if(dict.get('Rent')==None):
        dict['Rent']=rent_med

    if(dict.get('Size')==None):
        dict['Size']=size_med
    
    if(dict.get('Floor')==None):
        dict['Floor']="1 of 2"
    
    return dict

In [34]:
def convert_for_clustering(df,scaler):
    df['Rent']=np.log1p(df['Rent'])
    df['Size']=np.log1p(df['Size'])

    df['Area Type_Built Area'] = (df['Area Type'] == 'Built Area').astype(int)
    df['Area Type_Carpet Area'] = (df['Area Type'] == 'Carpet Area').astype(int)
    df['Area Type_Super Area'] = (df['Area Type'] == 'Super Area').astype(int)

    df['Furnishing Status_Furnished']= (df['Furnishing Status']=='Furnished').astype(int)
    df['Furnishing Status_Unfurnished']= (df['Furnishing Status']=='Unfurnished').astype(int)
    df['Furnishing Status_Semi-Furnished']= (df['Furnishing Status']=='Semi-Furnished').astype(int)

    df['Tenant Preferred_Bachelors/Family']=(df['Tenant Preferred']=='Bachelors/Family').astype(int)
    df['Tenant Preferred_Bachelors']=(df['Tenant Preferred']=='Bachelors').astype(int)
    df['Tenant Preferred_Family']=(df['Tenant Preferred']=='Family').astype(int)

    df[['current_floor', 'total_floors']] = df['Floor'].str.extract(r'(\w+)\s*out of\s*(\d+)')
    df['current_floor'] = df['current_floor'].replace(['Ground','Basement'], 0)

    df['current_floor'] = df['current_floor'].astype(int)
    df['total_floors'] = df['total_floors'].astype(int)
    df=df.drop(['Floor','Area Type','Furnishing Status','Tenant Preferred'],axis=1)

    df['floor_ratio'] = df['current_floor'] / df['total_floors']
    df.drop(['current_floor', 'total_floors'], axis=1, inplace=True)


    df[['Rent','Size','BHK']]=scaler.transform(df[['Rent','Size','BHK']])
    return df

In [35]:
dft2=handle_missing(data2)
dft2

{'BHK': 1,
 'Rent': 15000,
 'Size': 850,
 'Floor': '1 out of 2',
 'Area Type': 'Built Area',
 'Furnishing Status': 'Semi-Furnished',
 'Tenant Preferred': None}

In [36]:
dft2=pd.DataFrame([dft2])
dft2

   BHK   Rent  Size       Floor   Area Type Furnishing Status Tenant Preferred
0    1  15000   850  1 out of 2  Built Area    Semi-Furnished             None

In [37]:
dft=convert_for_clustering(dft,scaler)
dft

,BHK,Rent,Size,Area Type_Built Area,Area Type_Carpet Area,Area Type_Super Area,Furnishing Status_Furnished,Furnishing Status_Unfurnished,Furnishing Status_Semi-Furnished,Tenant Preferred_Bachelors/Family,Tenant Preferred_Bachelors,Tenant Preferred_Family,floor_ratio
0,-1.305168,-0.529030,-0.784514,0,1,0,0,0,1,0,0,1,0.400000
1,-0.106786,-0.096873,-0.163918,0,0,1,1,0,0,0,0,1,0.666667
2,1.091595,0.015425,0.471349,1,0,0,1,0,0,0,0,1,0.000000
3,-1.305168,-0.723349,-0.949858,0,1,0,0,1,0,0,1,0,0.666667
4,-0.106786,0.015425,0.023726,0,0,1,0,0,1,1,0,0,0.375000
5,1.091595,0.447594,0.706217,0,0,1,1,0,0,0,0,1,0.812500
6,-1.305168,-0.835641,-0.066970,0,1,0,0,1,0,0,1,0,0.750000
7,-0.106786,0.117012,0.108929,0,0,1,1,0,0,0,0,1,0.200000
8,1.091595,0.335294,0.593677,0,1,0,0,0,1,0,0,1,0.375000
9,-0.106786,-0.291198,-0.268042,1,0,0,0,1,0,0,1,0,0.500000

In [38]:
dft2=convert_for_clustering(dft2,scaler)
dft2

,BHK,Rent,Size,Area Type_Built Area,Area Type_Carpet Area,Area Type_Super Area,Furnishing Status_Furnished,Furnishing Status_Unfurnished,Furnishing Status_Semi-Furnished,Tenant Preferred_Bachelors/Family,Tenant Preferred_Bachelors,Tenant Preferred_Family,floor_ratio
0,-1.305168,-0.291198,0.108929,1,0,0,0,0,1,0,0,0,0.5

In [39]:
y=dft.values
dft['Clusters']=kmeans.predict(y)

In [40]:
dft

,BHK,Rent,Size,Area Type_Built Area,Area Type_Carpet Area,Area Type_Super Area,Furnishing Status_Furnished,Furnishing Status_Unfurnished,Furnishing Status_Semi-Furnished,Tenant Preferred_Bachelors/Family,Tenant Preferred_Bachelors,Tenant Preferred_Family,floor_ratio,Clusters
0,-1.305168,-0.529030,-0.784514,0,1,0,0,0,1,0,0,1,0.400000,2
1,-0.106786,-0.096873,-0.163918,0,0,1,1,0,0,0,0,1,0.666667,4
2,1.091595,0.015425,0.471349,1,0,0,1,0,0,0,0,1,0.000000,0
3,-1.305168,-0.723349,-0.949858,0,1,0,0,1,0,0,1,0,0.666667,2
4,-0.106786,0.015425,0.023726,0,0,1,0,0,1,1,0,0,0.375000,4
5,1.091595,0.447594,0.706217,0,0,1,1,0,0,0,0,1,0.812500,1
6,-1.305168,-0.835641,-0.066970,0,1,0,0,1,0,0,1,0,0.750000,2
7,-0.106786,0.117012,0.108929,0,0,1,1,0,0,0,0,1,0.200000,0
8,1.091595,0.335294,0.593677,0,1,0,0,0,1,0,0,1,0.375000,1
9,-0.106786,-0.291198,-0.268042,1,0,0,0,1,0,0,1,0,0.500000,4

In [41]:
y2=dft2.values
dft2['Clusters']=kmeans.predict(y2)
dft2

,BHK,Rent,Size,Area Type_Built Area,Area Type_Carpet Area,Area Type_Super Area,Furnishing Status_Furnished,Furnishing Status_Unfurnished,Furnishing Status_Semi-Furnished,Tenant Preferred_Bachelors/Family,Tenant Preferred_Bachelors,Tenant Preferred_Family,floor_ratio,Clusters
0,-1.305168,-0.291198,0.108929,1,0,0,0,0,1,0,0,0,0.5,2

In [42]:
import joblib

joblib.dump(kmeans,'clusterer.pkl')
joblib.dump(scaler,'scaler_of_clusterer.pkl')

['scaler_of_clusterer.pkl']